### PR TITLE
Replace deprecated labels in multisite examples docs

### PR DESCRIPTION
**Pull request by dwrightmsft**
Label **failure-domain.beta.kubernetes.io/zone** is deprecated in favour of **topology.kubernetes.io/zone** in 1.17 - replaced in docs and tested successfully on AKS.

More details: https://kubernetes.io/docs/reference/labels-annotations-taints/#failure-domainbetakubernetesiozone

### CODE REVIEW

**Review by gaurav-splunk — APPROVED** [review]

**Review by smohan-splunk — APPROVED** [review]

**Comment by smohan-splunk** [comment]
@dwrightmsft Thank you for the PR. May I request you to please submit this [CLA agreement](https://www.splunk.com/en_us/form/contributions.html) before we merge this?

**Comment by dwrightmsft** [comment]
> @dwrightmsft Thank you for the PR. May I request you to please submit this [CLA agreement](https://www.splunk.com/en_us/form/contributions.html) before we merge this?

Hi, I have submitted this, thanks!

**Comment by smohan-splunk** [comment]
> @dwrightmsft Thanks for your patience so far. I tested the topology.kubernetes.io/zone label on EKS both on 1.16 & 1.17. Here are some findings:
> On 1.17, Nodes have both labels set, and hence either can be used in the Multisite Cluster setup
> 
> ```
> kubectl describe nodes | grep -e "Name:" -e "zone"
> Name:               ip-192-168-30-244.us-west-2.compute.internal
>                     failure-domain.beta.kubernetes.io/zone=us-west-2c
>                     topology.kubernetes.io/zone=us-west-2c
> Name:               ip-192-168-62-236.us-west-2.compute.internal
>                     failure-domain.beta.kubernetes.io/zone=us-west-2b
>                     topology.kubernetes.io/zone=us-west-2b
> Name:               ip-192-168-89-158.us-west-2.compute.internal
>                     failure-domain.beta.kubernetes.io/zone=us-west-2a
>                     topology.kubernetes.io/zone=us-west-2a
> ```
> 
> However on 1.16, the `topology.kubernetes.io` label isn't set, and attempting to use in the CR would lead to the pods being in Pending state
> 
> ```
> kubectl describe nodes | grep -e "Name:" -e "zone"
> Name:               ip-192-168-2-223.us-west-2.compute.internal
>                     failure-domain.beta.kubernetes.io/zone=us-west-2c
> Name:               ip-192-168-47-126.us-west-2.compute.internal
>                     failure-domain.beta.kubernetes.io/zone=us-west-2b
> Name:               ip-192-168-71-55.us-west-2.compute.internal
>                     failure-domain.beta.kubernetes.io/zone=us-west-2a
> ```
> 
> ```
> splunk-cm-cluster-master-0            0/1     Pending   0          22m
> ..
>   Type     Reason            Age                   From               Message
>   ----     ------            ----                  ----               -------
>   Warning  FailedScheduling  27s (x11 over 6m47s)  default-scheduler  0/3 nodes
> ```
> 
> One option we have is to update the docs to recommend newer label only for Kubernetes version 1.17 & above. Please let me know your thoughts

@dwrightmsft I have added a commit to indicate (in the notes, rather than the examples) that the label `topology.kubernetes.io` is applicable for 1.17 onwards. Please let me know if you are ok with this change

**Review by kumarajeet — APPROVED** [review]
Minor - may want to add a period (.) at the end of second bullet.

**Review by jryb — APPROVED** [review]

**Review by akondur — APPROVED** [review]

**Review by sgontla — APPROVED** [review]

**Review by kashok-splunk — APPROVED** [review]

**Pull request merged**
