### PR TITLE
Support for OLM and other things

### PR DESCRIPTION
**Pull request by mikedickey**
Fixed an old bug that resurfaced itself, causing the operator to fail in cluster-scope. Default client tries to cache all objects from all namespaces when WATCH_NAMESPACE is empty, causing auth failures. The fix bypasses this (broken) cache, allowing permissions to be approrpiately scoped to namespaces.

Added build/make_bundle.sh which uses the "operator-sdk generate csv" command to generate a splunk OLM bundle in the deploy/olm-catalog/splunk directory. This is executed as part of the "make generate" command.

You can now use OLM to install the splunk operator bundle to your Kubernetes cluster. If you do not have OLM installed, you can use "operator-sdk olm install" to install it (see "operator-sdk olm --help" for more). Once you have OLM installed, ensure that your ~/.kube/config context points to a clean namespace and then run "operator-sdk run --olm --manifests=deploy/olm-catalog/splunk --operator-version=0.1.0" Just delete the namespace when you are done testing.

All the deploy/*.yaml files are now sources used to construct the OLM bundle and/or standalone YAML installation files (which are generated via build/package.sh).

Removed deploy/cluster_operator.yaml and deploy/namespace_operator.yaml since these have become redundant files. They are no longer necessary because the build/package.sh script now constructs all the proper install/release YAML files from sources located in deploy/*.yaml.

Changed splunk:operator:namespace-manager from a ClusterRole to a Role, since this is easier for reuse across tools and it is not required to be a ClusterRole.

Removed splunk:operator:resource-manager from the YAML used for namespace-scoped installs, since it only is required for cluster-scoped.

These changes also made the "splunk-operator-rbac.yaml" install resource unnecessary, since CRDS are now the only cluster-admin resources that need to be installed for namespace-scoped deployments.

Note that these changes involve more YAML processing than what we previously did, so the "yq" utilitity is now a required development tool. Updated README for install instructions.

Added build/run_scorecard.sh script which can be used to run the operator-sdk scorecard test suite. You can also use "make scorecard" to run this. Note that this requires having OLM installed in your Kubernetes cluster and that your ~/.kube/config context points to a clean namespace. Also note that the "statusdescriptorstest" test currently fails due to missing descriptors for some
of the status fields. I didn't fix this because it would require a CRD update.

### CODE REVIEW

**Comment by mikedickey** [comment]
Fixes #64 by pinning a specific release tag to all the YAML install files

**Comment by mikedickey** [comment]
Fixes #66 and #24

**Comment by kelvinatsplunk** [comment]
Does this change means we cannot install splunk operator outside of OLM ?

**Comment by mikedickey** [comment]
> Does this change means we cannot install splunk operator outside of OLM ?

No, it's purely optional. You only need to have OLM installed to run the scorecard tests

**Comment by kelvinatsplunk** [comment]
I think we need to add "image" dependency to "package" target. I was running make package and it failed looking for splunk/splunk-operator:latest to tag.

**Comment by kelvinatsplunk** [comment]
In the release-xxx folder generated by make package, it seems like the files "splunk-operator-crds.yaml and splunk-operator-noadmin.yaml" are transient ? User only need to apply splunk-operator-cluster.yaml or -install.yaml. Can we remove them to avoid confusion ?

**Comment by mikedickey** [comment]
> In the release-xxx folder generated by make package, it seems like the files "splunk-operator-crds.yaml and splunk-operator-noadmin.yaml" are transient ? User only need to apply splunk-operator-cluster.yaml or -install.yaml. Can we remove them to avoid confusion ?

See https://github.com/splunk/splunk-operator/blob/olm-support/docs/Install.md#installation-by-a-regular-user

**Comment by mikedickey** [comment]
> I think we need to add "image" dependency to "package" target. I was running make package and it failed looking for splunk/splunk-operator:latest to tag.

I'll make sure I include this in my next push

**Pull request merged**
