### PR TITLE
Fix log warnings

### PR DESCRIPTION
**Pull request by akondur**
Fixing a couple of compiler warnings for fmt.Errorf. Used scopedLog for better visibility during runtime.

### CODE REVIEW

**Review by gaurav-splunk — APPROVED** [review]

**Comment by smohan-splunk** [comment]
> Fixing a couple of compiler warnings for fmt.Errorf. Used scopedLog for better visibility during runtime.

@akondur A couple of requests:
 - Can you please share the exact warning being fixed?
 - An example of the log post change to scopedLog would be nice

**Comment by akondur** [comment]
> > Fixing a couple of compiler warnings for fmt.Errorf. Used scopedLog for better visibility during runtime.
> 
> @akondur A couple of requests:
> 
> * Can you please share the exact warning being fixed?
> * An example of the log post change to scopedLog would be nice

**Comment by kashok-splunk** [comment]
@smohan-splunk  There was a warning "result of fmt.Errorf call not used" 
image

**Comment by akondur** [comment]
> > Fixing a couple of compiler warnings for fmt.Errorf. Used scopedLog for better visibility during runtime.
> 
> @akondur A couple of requests:
> 
> * Can you please share the exact warning being fixed?
> * An example of the log post change to scopedLog would be nice

Examples of scopedLog:

IDXC:
{"level":"error","ts":1601661216.195989,"logger":"splunk.enterprise.indexerClusterPodManager.getClusterMasterClient","msg":"Couldn't retrieve the admin password from pod","name":"example","namespace":"default","error":"Secret not found"}
{"level":"error","ts":1601661216.195989,"logger":"splunk.enterprise.indexerClusterPodManager.getClient","msg":"Couldn't retrieve the admin password from pod","name":"example","namespace":"default","error":"Secret not found"}

SHC:
{"level":"error","ts":1601661216.195989,"logger":"splunk.enterprise.searchHeadClusterPodManager.getClient","msg":"Couldn't retrieve the admin password from pod","name":"example","namespace":"default","error":"Secret not found"}

**Comment by smohan-splunk** [comment]
> @smohan-splunk There was a warning "result of fmt.Errorf call not used"
> image

I wonder if reading the result of `fmt.Errorf` into a variable would have helped resolve the warning, but `scopedLog` is a good alternative too.

**Review by smohan-splunk — APPROVED** [review]

**Pull request merged**
