### PR TITLE
Expose port 8088 on indexers for HEC

### PR DESCRIPTION
**Pull request by mikedickey**
Expose port 8088 on indexers for HEC

Also, only expose ports for DFC (DFS component) on search heads

### CODE REVIEW

**Comment by mikedickey** [comment]
I tested this by adding a few defaults parameters in a SplunkEnterprise deployment:

```defaults: |-
    splunk:
      hec_disabled: 0
      hec_enableSSL: 0
      hec_token: "abcd-1234-efgh-5678"
```

Note that you can expose HEC by linking ingress rules to port 8088 of the splunk-*-indexer-headless service:

```
- host: splunk-hec.eksdemo.splenti.io
    http:
      paths:
      - backend:
          serviceName: splunk-dfscluster-indexer-headless
          servicePort: 8088
```

```
curl https://.../services/collector -H "Authorization: Splunk abcd-1234-efgh-5678" -d '{"event": "Hello, world!", "sourcetype": "manual"}'
{"text":"Success","code":0}%
```

**Comment by mikedickey** [comment]
Fixes #1

**Comment by aegershman** [comment]
This might be an obvious answer, but in the Ingress example...

```yml
- host: ...
    http:
      paths:
      - backend:
          serviceName: splunk-dfscluster-indexer-headless
          servicePort: 8088
```

Would the actual value of the `path` be `/services/collector`? e.g.,

```yml
- host: ...
    http:
      paths:
      - backend:
          serviceName: splunk-dfscluster-indexer-headless
          servicePort: 8088
        path: /services/collector
```

**Comment by mikedickey** [comment]
@aegershman For the example, adding `path: /services/collector` would be optional and I believe it would just eliminate having to include that path in your HTTP requests to the endpoint. Not sure if there's any pros/cons to being able to hit other endpoints on 8088.

Yes, I think it's best to use ingress to terminate TLS because of all the benefits one can get out of cert-manager. I imagine you could also encrypt the channel between the nginx proxies and the indexer pods by setting hec_enableSSL to 1.

**Pull request merged**
