### PR TITLE
Update SmartStore.md

### PR DESCRIPTION
**Pull request by rajeshvijayarajan**
Misplaced quotes in the proposed command-line for creating a secret to hold the smart store credentials.

### CODE REVIEW

**Comment by sgontla** [comment]
@rajeshvijayarajan do you face any issue with the existing way of creating a secret object? I think we can use either format. As an example here at: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure

**Comment by rajeshvijayarajan** [comment]
Interesting. That wasn't my experience though. I was able to reproduce the issue again as well. See below:

```
C:\Users\Administrator\Downloads\splunk\splunk-yml>kubectl create secret generic ss-secret --from-literal='s3_access_key=O9I071G7ADRH4KDWG9C9' --from-literal='s3_secret_key=YZ9J43ks47btSEvQyUcUT4SMSSpjJEiI0y3bhmq3'
error: "'s3_access_key" is not a valid key name for a Secret: a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')

C:\Users\Administrator\Downloads\splunk\splunk-yml>kubectl create secret generic ss-secret --from-literal=s3_access_key='O9I071G7ADRH4KDWG9C9' --from-literal=s3_secret_key='YZ9J43ks47btSEvQyUcUT4SMSSpjJEiI0y3bhmq3'
secret/ss-secret created
```

**Comment by rajeshvijayarajan** [comment]
I now realize even my proposal is flawed. What's need instead is a version that does not use quotes!

With my earlier proposed change, the quotes get included in the value, which lands up in the indexes.conf and messes up the access of the S3-compatible store. 

So, here is what worked well.

```
kubectl create secret generic smart-store-secret --from-literal=s3_access_key=O9I071G7ADRH4KDWG9C9 --from-literal=s3_secret_key=YZ9J43ks47btSEvQyUcUT4SMSSpjJEiI0y3bhmq3
```

**Comment by sgontla** [comment]
Thanks, @rajeshvijayarajan. It seems like the issue is specific to the Kubectl command usage on Windows? Also, may I know what type of K8 cluster(EKS, kind, K3s..?) you are using? do you mind sharing the "kubectl version"?

Removing the quotes is fine if that is causing an issue with kubectl on Windows.

**Review by akondur — APPROVED** [review]

**Comment by rajeshvijayarajan** [comment]
Sure, the flavor of K8s is HPE Ezmeral Container Platform 5.3. The k8s cluster and kubectl version is 1.20.2

```
C:\Users\Administrator\Downloads\splunk\splunk-yml>kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sgontla** [comment]
@rajeshvijayarajan , thanks for the info. You may want to update your PR without quotes? Alternatively, let me know if want me to do it.

**Comment by rajeshvijayarajan** [comment]
Thanks @sgontla - I have updated the pull request. Cheers!

**Review by sgontla — APPROVED** [review]

**Comment by smohan-splunk** [comment]
@rajeshvijayarajan Thanks for the PR & discussions. Before we merge this, may I request you to please submit this [CLA agreement](https://www.splunk.com/en_us/form/contributions.html)? Once filled, please let me know and I will go ahead with the merge.

**Review by gaurav-splunk — APPROVED** [review]

**Comment by smohan-splunk** [comment]
> @rajeshvijayarajan Thanks for the PR & discussions. Before we merge this, may I request you to please submit this [CLA agreement](https://www.splunk.com/en_us/form/contributions.html)? Once filled, please let me know and I will go ahead with the merge.

@rajeshvijayarajan Just following up here, please let me know once the CLA agreement has been filled.

**Comment by rajeshvijayarajan** [comment]
I have submitted the CLA. Cheers!

**Pull request merged**
